// react-sample/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import DevDay from './DevDay'

class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      napoli: true,
      salerno: false,
      benevento: false
    };
    this.select = this.select.bind(this);
  }

  select(id) {
    this.setState({
      napoli: id=== 'napoli',
      salerno: id === 'salerno',
      benevento: id === 'benevento'
    });
  }

  render() {
    return (
      <div className="App">
       <DevDay id="napoli" select={this.state.napoli} onSelect={this.select} city="Napoli" />
       <DevDay id="salerno" select={this.state.salerno} onSelect={this.select} city="Salerno" />
       <DevDay id="benevento" select={this.state.benevento} onSelect={this.select} city="Benevento" />
      </div>
    );
  }
}

export default App;

// angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  napoli: boolean;
  salerno: boolean;
  benevento: boolean;

  select(id: string) {
    if (id === 'napoli') {
      this.napoli = true;
      this.salerno = false;
      this.benevento = false;
    }
     if (id === 'benevento') {
      this.napoli = false;
      this.salerno = false;
      this.benevento = true;
    }
     if (id === 'salerno') {
      this.napoli = false;
      this.salerno = true;
      this.benevento = false;
    }
  }


}

<div>
  <app-devday [selected]="napoli" city="Napoli" (onSelected)="select('napoli')"></app-devday>
  <app-devday [selected]="salerno" city="Salerno" (onSelected)="select('salerno')"></app-devday>
  <app-devday [selected]="benevento" city="Benevento" (onSelected)="select('benevento')"></app-devday>
</div>
